[package]
name = "uclicious-example"
version = "0.1.0"
authors = ["Andrey Cherkashin <with.out@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uclicious-derive = { path = "../uclicious-derive" }